#!/bin/bash

# pics dir
PICTURES="$HOME/Pictures/"

# get sorted by time latest ss
LATEST_PICTURE=$(ls ${PICTURES} -tr | tail -1)
LATEST_PICTURE=${PICTURES}${LATEST_PICTURE}

# copy to curr location
cp ${LATEST_PICTURE} $PWD
