require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
-- require "user.neosolarized"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.hexokinase"
--require "user.comment"
require "user.comments"
require "user.gitsigns"
require "user.todocomments"
-- require "user.nvim-tree"
require "user.new_nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
-- require "user.alpha"
require "user.startify"
require "user.whichkey"
require "user.vimwiki"
require "user.autocommands"
